# Generated by Django 5.0 on 2024-12-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpi', '0001_initial'),
        ('utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='laborantin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='utilisateur.laborantin'),
        ),
        migrations.AddField(
            model_name='bilanbiologiquelaborantin',
            name='bilan_bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.bilanbiologique'),
        ),
        migrations.AddField(
            model_name='bilanbiologiquelaborantin',
            name='laborantin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.laborantin'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='bilan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_radiologique', to='dpi.bilan'),
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='radiologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='utilisateur.radiologue'),
        ),
        migrations.AddField(
            model_name='bilanradiologiqueradiologue',
            name='bilan_rad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.bilanradiologique'),
        ),
        migrations.AddField(
            model_name='bilanradiologiqueradiologue',
            name='radiologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.radiologue'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='utilisateur.medecin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='utilisateur.medecin'),
        ),
        migrations.AddField(
            model_name='consultationmedecin',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.consultation'),
        ),
        migrations.AddField(
            model_name='consultationmedecin',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.medecin'),
        ),
        migrations.AddField(
            model_name='consultationoutil',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.consultation'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.patient'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='utilisateur.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dpi.dpi'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='dpi.dpi'),
        ),
        migrations.AddField(
            model_name='antecedant',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi'),
        ),
        migrations.AddField(
            model_name='dpisoin',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.dpi'),
        ),
        migrations.AddField(
            model_name='examen',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.consultation'),
        ),
        migrations.AddField(
            model_name='bilan',
            name='examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bilan', to='dpi.examen'),
        ),
        migrations.AddField(
            model_name='graphiquetendance',
            name='bilan_biologique',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graphique_tendance', to='dpi.bilanbiologique'),
        ),
        migrations.AddField(
            model_name='dpi',
            name='hopital_initial',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi.hopital'),
        ),
        migrations.AddField(
            model_name='decompte',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.hopital'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.hopital'),
        ),
        migrations.AddField(
            model_name='hopitalutilisateur',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.hopital'),
        ),
        migrations.AddField(
            model_name='hopitalutilisateur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitazliation',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.administratif'),
        ),
        migrations.AddField(
            model_name='hospitazliation',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.hopital'),
        ),
        migrations.AddField(
            model_name='hospitazliation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.patient'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='dpi.consultation'),
        ),
        migrations.AddField(
            model_name='ordonnancemedicament',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.medicament'),
        ),
        migrations.AddField(
            model_name='ordonnancemedicament',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.ordonnance'),
        ),
        migrations.AddField(
            model_name='consultationoutil',
            name='outil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.outil'),
        ),
        migrations.AddField(
            model_name='soin',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='dpi.dpi'),
        ),
        migrations.AddField(
            model_name='dpisoin',
            name='soin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.soin'),
        ),
    ]
