# Generated by Django 5.0 on 2024-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='date_debut_service',
            field=models.DateField(),
        ),
    ]
