# Generated by Django 5.0 on 2024-12-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soin',
            old_name='name',
            new_name='nom',
        ),
    ]
