# Generated by Django 5.0 on 2024-12-22 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dpi", "0001_initial"),
        ("utilisateur", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bilanbiologique",
            name="laborantin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilans",
                to="utilisateur.laborantin",
            ),
        ),
        migrations.AddField(
            model_name="bilanbiologiquelaborantin",
            name="bilan_bio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.bilanbiologique"
            ),
        ),
        migrations.AddField(
            model_name="bilanbiologiquelaborantin",
            name="laborantin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.laborantin"
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologique",
            name="radiologue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilans",
                to="utilisateur.radiologue",
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologiqueradiologue",
            name="bilan_rad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.bilanradiologique"
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologiqueradiologue",
            name="radiologue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.radiologue"
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificats",
                to="utilisateur.medecin",
            ),
        ),
        migrations.AddField(
            model_name="consultationmedecin",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.consultation"
            ),
        ),
        migrations.AddField(
            model_name="consultationmedecin",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.medecin"
            ),
        ),
        migrations.AddField(
            model_name="consultationoutil",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.consultation"
            ),
        ),
        migrations.AddField(
            model_name="decompte",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.patient"
            ),
        ),
        migrations.AddField(
            model_name="dpi",
            name="contact_urgence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dpis",
                to="dpi.contacturgence",
            ),
        ),
        migrations.AddField(
            model_name="dpi",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossier_patient",
                to="utilisateur.patient",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="dpi.dpi",
            ),
        ),
        migrations.AddField(
            model_name="certificat",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificats",
                to="dpi.dpi",
            ),
        ),
        migrations.AddField(
            model_name="antecedant",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.dpi"
            ),
        ),
        migrations.AddField(
            model_name="dpisoin",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.dpi"
            ),
        ),
        migrations.AddField(
            model_name="dpisoin",
            name="infermier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.infermier"
            ),
        ),
        migrations.AddField(
            model_name="examen",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.consultation"
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologique",
            name="examen",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.examen"
            ),
        ),
        migrations.AddField(
            model_name="bilanbiologique",
            name="examen",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.examen"
            ),
        ),
        migrations.AddField(
            model_name="graphiquetendance",
            name="bilan_biologique",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphiqus",
                to="dpi.bilanbiologique",
            ),
        ),
        migrations.AddField(
            model_name="dpisoin",
            name="hopital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.hopital"
            ),
        ),
        migrations.AddField(
            model_name="dpi",
            name="hopital_initial",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dpi.hopital",
            ),
        ),
        migrations.AddField(
            model_name="decompte",
            name="hopital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.hopital"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="hopital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.hopital"
            ),
        ),
        migrations.AddField(
            model_name="hopitalutilisateur",
            name="hopital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.hopital"
            ),
        ),
        migrations.AddField(
            model_name="hopitalutilisateur",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hospitalisation",
            name="cree_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="utilisateur.administratif",
            ),
        ),
        migrations.AddField(
            model_name="hospitalisation",
            name="hopital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.hopital"
            ),
        ),
        migrations.AddField(
            model_name="hospitalisation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.patient"
            ),
        ),
        migrations.AddField(
            model_name="mutuelle",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutuelles",
                to="utilisateur.patient",
            ),
        ),
        migrations.AddField(
            model_name="ordonnance",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordonnances",
                to="dpi.consultation",
            ),
        ),
        migrations.AddField(
            model_name="consultationoutil",
            name="outil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.outil"
            ),
        ),
        migrations.AddField(
            model_name="parametrevaleur",
            name="bilan_biologique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.bilanbiologique"
            ),
        ),
        migrations.AddField(
            model_name="parametrevaleur",
            name="parametre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.parametre"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.medicament"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="ordonnance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.ordonnance"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.consultation"
            ),
        ),
        migrations.AddField(
            model_name="resumemesuresprises",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mesures",
                to="dpi.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumesymptomes",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="symptomes",
                to="dpi.resume",
            ),
        ),
        migrations.AddField(
            model_name="dpisoin",
            name="soin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.soin"
            ),
        ),
        migrations.AddField(
            model_name="soininfermier",
            name="infermier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="utilisateur.infermier"
            ),
        ),
        migrations.AddField(
            model_name="soininfermier",
            name="soin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dpi.soin"
            ),
        ),
    ]
