# Generated by Django 5.0 on 2024-12-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecin_principal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mes_consultations', to='utilisateur.medecin'),
            preserve_default=False,
        ),
    ]
