# Generated by Django 5.0 on 2024-12-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='hopital_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpi.hopital'),
        ),
    ]
