# Generated by Django 5.0 on 2024-12-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_consultation_medecin_principal'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmedecin',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='dpi.consultation'),
        ),
        migrations.AlterField(
            model_name='consultationmedecin',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='utilisateur.medecin'),
        ),
    ]
