# Generated by Django 5.0 on 2024-12-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='bilan',
        ),
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='bilan',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='examen',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpi.examen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='examen',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpi.examen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='resultats',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='type',
            field=models.CharField(choices=[('biologique', 'Biologique'), ('radiologique', 'Radiologique')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bilan',
        ),
    ]
