# Generated by Django 5.1.4 on 2024-12-14 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_mutuelle_parametre_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='date_création',
        ),
        migrations.AddField(
            model_name='dpi',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soin',
            name='type_soin',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
