# Generated by Django 5.0 on 2024-12-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0004_alter_consultationmedecin_consultation_and_more'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medecin_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_consultations', to='utilisateur.medecin'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='resultats',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
