# Generated by Django 5.1.4 on 2024-12-14 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0004_remove_dpi_date_création_dpi_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompte',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='date_debut_service',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hopitalutilisateur',
            name='date_adhesion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_entree',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date_sortie',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_prochaine_consultation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='soin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
