# Generated by Django 5.1.4 on 2024-12-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0005_alter_decompte_date_alter_hopital_date_debut_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dpi.resume'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.prescription'),
        ),
    ]
