# Generated by Django 5.1.4 on 2024-12-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0006_alter_consultation_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dpi.resume'),
        ),
    ]
