# Generated by Django 5.0 on 2024-12-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_alter_dpi_hopital_initial'),
        ('dpi', '0006_alter_prescription_medicament_and_more'),
    ]

    operations = [
    ]
