# Generated by Django 5.1.4 on 2024-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0007_alter_consultation_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='duree',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
