# Generated by Django 5.1.4 on 2024-12-14 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0008_alter_prescription_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='nombre_de_prises',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
