# Generated by Django 5.0 on 2024-12-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0009_alter_prescription_nombre_de_prises'),
        ('utilisateur', '0004_remove_patient_contact_urgence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='prescription',
        ),
        migrations.AddField(
            model_name='mutuelle',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mutuelles', to='utilisateur.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='ordonnance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpi.ordonnance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dpi.consultation'),
            preserve_default=False,
        ),
    ]
