# Generated by Django 5.0 on 2024-12-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_initial'),
        ('dpi', '0010_remove_consultation_resume_and_more'),
    ]

    operations = [
    ]
