# Generated by Django 5.0 on 2024-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administratif', 'Administratif'), ('patient', 'Patient'), ('medecin', 'Medecin'), ('infermier', 'Infermier'), ('radiologue', 'Radiologue'), ('laborantin', 'Laborantin'), ('adminsystem', 'Adminsystem')], default='patient', max_length=16),
        ),
    ]
