# Generated by Django 5.1.4 on 2024-12-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_mutuelle_parametre_resume_and_more'),
        ('utilisateur', '0002_alter_utilisateur_managers_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_urgence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi.contacturgence'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mutuelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpi.mutuelle'),
        ),
    ]
