# Generated by Django 5.0 on 2024-12-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_patient_mutuelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mutuelle',
        ),
    ]
