# Generated by Django 5.0 on 2024-12-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_patient_contact_urgence_alter_patient_mutuelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_urgence',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mutuelle',
        ),
    ]
